[namespace]
name = "wasi"
registry = "ghcr.io/webassembly"

[[interface]]
name = "io"
repository = "wasi/io"

[[interface]]
name = "clocks"
repository = "wasi/clocks"

[[interface]]
name = "http"
repository = "wasi/http"

[[interface]]
name = "random"
repository = "wasi/random"

[[interface]]
name = "filesystem"
repository = "wasi/filesystem"

[[interface]]
name = "sockets"
repository = "wasi/sockets"

[[interface]]
name = "cli"
repository = "wasi/cli"

[[interface]]
name = "otel"
repository = "wasi/otel"

[[interface]]
name = "config"
repository = "wasi/config"

[[interface]]
name = "logging"
repository = "wasi/logging"

[[interface]]
name = "keyvalue"
repository = "wasi/keyvalue"

[[interface]]
name = "blobstore"
repository = "wasi/blobstore"

[[interface]]
name = "webgpu"
repository = "wasi/webgpu"
