//! A package manager for WebAssembly components.
//!
//! This crate provides functionality to pull, store, and manage WebAssembly
//! component packages from OCI registries.
//!
//! # Example
//!
//! ```no_run
//! use component_package_manager::Config;
//! use component_package_manager::manager::Manager;
//! use std::path::Path;
//!
//! #[tokio::main]
//! async fn main() -> anyhow::Result<()> {
//!     // Open the package manager (uses default config and cache location)
//!     let manager = Manager::open().await?;
//!
//!     // Pull a WebAssembly package from an OCI registry
//!     let reference = "ghcr.io/webassembly/wasi/clocks:0.2.0".parse()?;
//!     let result = manager.pull(reference).await?;
//!     println!("Pull result: {:?}", result.insert_result);
//!
//!     // Install a package by vendoring its layers into a local directory
//!     let reference = "ghcr.io/webassembly/wasi/clocks:0.2.0".parse()?;
//!     let install = manager.install(reference, Path::new("vendor")).await?;
//!     for path in &install.vendored_files {
//!         println!("Installed: {}", path.display());
//!     }
//!
//!     // List all cached images
//!     let images = manager.list_all().await?;
//!     for image in &images {
//!         println!("{} ({} bytes)", image.reference(), image.size_on_disk);
//!     }
//!
//!     Ok(())
//! }
//! ```

/// WAC-based component composition (requires the `compose` feature).
#[cfg(feature = "compose")]
pub mod compose;
mod config;
mod convert;
mod credential_helper;
/// Core manager functionality for pulling, installing, and listing packages.
pub mod manager;
pub mod oci;
/// Permission resolution for running WebAssembly components.
pub mod permissions;
mod progress;
/// Publish helpers: build a [`crate::publish::PublishPlan`] from a
/// `wasm.toml` manifest and push the artifact to an OCI registry.
pub mod publish;
/// Dependency resolver using the PubGrub version-solving algorithm.
pub mod resolver;
/// Storage layer for persisting package metadata and state.
pub mod storage;
pub mod types;
mod xdg;

pub use config::{Config, RegistryConfig, RunConfig};
pub use credential_helper::{CredentialError, CredentialHelper};
pub use oci_client::Reference;
pub use progress::ProgressEvent;
pub(crate) use xdg::xdg_config_home;

/// Parse an OCI reference string, stripping the optional `oci://` scheme prefix.
///
/// Accepts both bare references (e.g. `ghcr.io/owner/repo:tag`) and
/// references with the `oci://` scheme (e.g. `oci://ghcr.io/owner/repo:tag`).
///
/// # Examples
///
/// ```rust
/// use component_package_manager::parse_reference;
///
/// let r = parse_reference("ghcr.io/owner/repo:latest").unwrap();
/// assert_eq!(r.repository(), "owner/repo");
///
/// let r = parse_reference("oci://ghcr.io/owner/repo:latest").unwrap();
/// assert_eq!(r.repository(), "owner/repo");
/// ```
pub fn parse_reference(s: &str) -> Result<Reference, String> {
    let s = s.strip_prefix("oci://").unwrap_or(s);
    s.parse::<Reference>().map_err(|e| e.to_string())
}

/// Write a lockfile to disk with a header comment.
///
/// The lockfile is prefixed with a comment indicating it is auto-generated
/// and should not be manually edited.
///
/// # Errors
///
/// Returns an I/O error if writing to the file system fails.
pub async fn write_lock_file<P: AsRef<std::path::Path>>(
    path: P,
    lock: &component_manifest::Lockfile,
) -> std::io::Result<()> {
    let header = "# This file is automatically generated by component(1).\n\
                  # It should not be manually edited.\n";
    let body = toml::to_string_pretty(lock).map_err(std::io::Error::other)?;
    let contents = format!("{header}\n{body}");
    tokio::fs::write(path.as_ref(), contents).await
}

/// Format a byte size as a human-readable string (B, KB, MB, GB).
///
/// # Examples
///
/// ```rust
/// use component_package_manager::format_size;
///
/// assert_eq!(format_size(0), "0 B");
/// assert_eq!(format_size(1024), "1.00 KB");
/// assert_eq!(format_size(1_048_576), "1.00 MB");
/// assert_eq!(format_size(1_073_741_824), "1.00 GB");
/// ```
// r[impl format.size.bytes]
// r[impl format.size.kilobytes]
// r[impl format.size.megabytes]
// r[impl format.size.gigabytes]
#[must_use]
pub fn format_size(bytes: u64) -> String {
    const KB: u64 = 1024;
    const MB: u64 = KB * 1024;
    const GB: u64 = MB * 1024;

    if bytes >= GB {
        let (whole, frac) = (bytes / GB, (bytes % GB) * 100 / GB);
        format!("{whole}.{frac:02} GB")
    } else if bytes >= MB {
        let (whole, frac) = (bytes / MB, (bytes % MB) * 100 / MB);
        format!("{whole}.{frac:02} MB")
    } else if bytes >= KB {
        let (whole, frac) = (bytes / KB, (bytes % KB) * 100 / KB);
        format!("{whole}.{frac:02} KB")
    } else {
        format!("{bytes} B")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // r[verify format.size.bytes]
    #[test]
    fn test_format_size_bytes() {
        assert_eq!(format_size(0), "0 B");
        assert_eq!(format_size(1), "1 B");
        assert_eq!(format_size(512), "512 B");
        assert_eq!(format_size(1023), "1023 B");
    }

    // r[verify format.size.kilobytes]
    #[test]
    fn test_format_size_kilobytes() {
        assert_eq!(format_size(1024), "1.00 KB");
        assert_eq!(format_size(1536), "1.50 KB");
        assert_eq!(format_size(2048), "2.00 KB");
        assert_eq!(format_size(1024 * 1023), "1023.00 KB");
    }

    // r[verify format.size.megabytes]
    #[test]
    fn test_format_size_megabytes() {
        assert_eq!(format_size(1024 * 1024), "1.00 MB");
        assert_eq!(format_size(1024 * 1024 + 512 * 1024), "1.50 MB");
        assert_eq!(format_size(1024 * 1024 * 100), "100.00 MB");
    }

    // r[verify format.size.gigabytes]
    #[test]
    fn test_format_size_gigabytes() {
        assert_eq!(format_size(1024 * 1024 * 1024), "1.00 GB");
        assert_eq!(format_size(1024 * 1024 * 1024 * 2), "2.00 GB");
        assert_eq!(
            format_size(1024 * 1024 * 1024 + 512 * 1024 * 1024),
            "1.50 GB"
        );
    }
}
